image: docker

services:
    - docker

before_script:
    - sudo apt-get install -y python-pip
    - pip install docker-compose
    - pip install flake8

deploy:
    script:
        - docker-compose run app sh -c "python manage.py test && flake8"