image: docker

services:
    - docker

before_script:
    - sudo apt-get install -y python-pip
    - echo "TEST1 to see which directory we are in"
    - pwd

deploy:
    script:
        - docker-compose run --rm app sh -c "python manage.py test && flake8"
